### ISSUE TITLE
There appears to be no way to supply a username/password for the chosen server.

### ISSUE THREAD

**Issue by markrvmurray** [Kinwailo/ngroup#1]
I’ve attached to news.eternal-september.org:119, but I cannot find a way to supply my username/password. Does this exist? I can’t even select the usual cogwheel icon for such things.

Thanks!

M

**Comment by Kinwailo** [comment]
This is not supported because I don't know any server with this feature for test. By the way, if I can register an account in news.eternal-september.org, I will add this feature.

**Comment by Kinwailo** [comment]
Username/password is supported in new version.

**Comment by Kinwailo** [comment]
Username/password is supported in new version.
